on:
  push:
    branches:
      - main

name: Docs

jobs:
  docs:
    name: Build and deploy documentation
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
      - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2
      - name: Build rustdoc
        run: cargo doc --all-features --workspace
      - name: Organize
        run: |
          rm -rf target/gh-pages
          mkdir target/gh-pages
          mv target/doc target/gh-pages/rustdoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@800bbc83122db9d4c38fcd284782d5afe62e52df # releases/v4
        with:
          branch: gh-pages
          folder: target/gh-pages
          single-commit: true
